stages:
  data_ingestion:
    cmd: python Code/data_ingestion.py
    deps:
    - Code/data_ingestion.py
    params:
    - data_ingestion.test_size
    outs:
    - data/raw

  data_preprocessing:
    cmd: python Code/data_preprocessing.py
    deps:
    - Code/data_preprocessing.py
    - data/raw
    outs:
    - data/processed
  feature_engineering:
    cmd: python Code/feature_engineering.py
    deps:
    - Code/feature_engineering.py
    - data/processed
    params:
    - feature_engineering.max_features
    outs:
    - data/features
  model_building:
    cmd: python Code/model_building.py
    deps:
    - Code/model_building.py
    - data/features
    params:
    - model_building.n_estimators
    - model_building.learning_rate
    outs:
    - model.pkl
  model_evaluation:
    cmd: python Code/model_evaluation.py
    deps:
    - Code/model_evaluation.py
    - model.pkl
    metrics:
    - metrics.json
